CREATE TABLE IF NOT EXISTS `t_ozon_listing_draft` (
  `id` bigint unsigned NOT NULL,
  `auth_id` bigint unsigned NOT NULL COMMENT '授权ID',
  `shop_id` bigint unsigned NOT NULL COMMENT '店铺ID',
  `draft_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '草稿名称',
  `description_category_id` bigint unsigned DEFAULT NULL COMMENT '类目ID',
  `description_category_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '类目名称',
  `type_id` bigint unsigned DEFAULT NULL COMMENT '类型ID',
  `type_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '类型名称',
  `title_source_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP标题快照',
  `title_override_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '运营覆盖标题',
  `brand_source_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP品牌快照',
  `brand_override_value` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '运营覆盖品牌',
  `description_source_value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'ERP描述快照',
  `description_override_value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT '运营覆盖描述',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'DRAFT' COMMENT '草稿状态',
  `last_preview_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '最近预览状态',
  `last_preview_message` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '最近预览消息',
  `last_publish_task_id` bigint unsigned DEFAULT NULL COMMENT '最近发布任务ID',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_auth_status` (`auth_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Ozon刊登草稿头表';
