CREATE TABLE IF NOT EXISTS `t_ozon_listing_variant` (
  `id` bigint unsigned NOT NULL,
  `draft_id` bigint unsigned NOT NULL COMMENT '草稿ID',
  `auth_id` bigint unsigned NOT NULL COMMENT '授权ID',
  `shop_id` bigint unsigned NOT NULL COMMENT '店铺ID',
  `material_sku` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT 'ERP SKU',
  `material_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT 'ERP商品名',
  `offer_id_override` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '运营覆盖Offer ID',
  `barcode_override` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '运营覆盖条码',
  `price_source_value` decimal(18,2) DEFAULT NULL COMMENT 'ERP价格快照',
  `price_override` decimal(18,2) DEFAULT NULL COMMENT '运营覆盖价格',
  `weight_source_value` decimal(18,3) DEFAULT NULL COMMENT 'ERP重量快照',
  `weight_override_value` decimal(18,3) DEFAULT NULL COMMENT '运营覆盖重量',
  `length_source_value` decimal(18,2) DEFAULT NULL COMMENT 'ERP长度快照',
  `length_override_value` decimal(18,2) DEFAULT NULL COMMENT '运营覆盖长度',
  `width_source_value` decimal(18,2) DEFAULT NULL COMMENT 'ERP宽度快照',
  `width_override_value` decimal(18,2) DEFAULT NULL COMMENT '运营覆盖宽度',
  `height_source_value` decimal(18,2) DEFAULT NULL COMMENT 'ERP高度快照',
  `height_override_value` decimal(18,2) DEFAULT NULL COMMENT '运营覆盖高度',
  `variant_label` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '变体标签',
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'DRAFT' COMMENT '变体状态',
  `last_sync_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '最近同步状态',
  `last_sync_message` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL COMMENT '最近同步消息',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_draft_material_sku` (`draft_id`,`material_sku`),
  KEY `idx_auth_draft` (`auth_id`,`draft_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='Ozon刊登变体表';
